import test from 'node:test';
import assert from 'node:assert/strict';
import {parseHTML} from '../web/node_modules/linkedom/esm/index.js';
import {amount,allowedProduct,sameProduct,parsePrice,advantage} from '../supabase/functions/homepage-refresh/price.mjs';
import {eligible,catalogueEligible,safeDestination,validListingId} from '../web/lib/policy.ts';
const now=Date.parse('2026-10-08T19:00:00Z');
const base={title:"Test product",id:'2efce27b-bfef-41bf-9bec-6741c1b73616',status:'verified',checked_at:new Date(now-1000).toISOString(),price:400,competitor_price:600,product_url:'https://www.amazon.com.tr/dp/B0CZ47VFR1',affiliate_url:'https://www.amazon.com.tr/dp/B0CZ47VFR1?tag=anlikindirimr-21&linkCode=ll1',merchant_slug:'amazon'};
test('fresh eligible snapshot and full affiliate query are preserved',()=>{assert.equal(eligible(base,now),true);assert.equal(safeDestination(base.affiliate_url,'amazon'),base.affiliate_url);});
test('stale, missing, failed, expired and future-dated checks are hidden',()=>{for(const r of [{...base,checked_at:new Date(now-3600000).toISOString()},{...base,checked_at:null},{...base,status:'unverified'},{...base,status:'ended'},{...base,expires_at:'2026-10-08T18:00:00Z'},{...base,checked_at:new Date(now+60000).toISOString()}])assert.equal(eligible(r,now),false);});
test('15 percent minimum and suspicious 70 percent gap boundaries',()=>{assert.equal(advantage(850,1000),15);assert.equal(advantage(851,1000),null);assert.equal(advantage(300,1000),null);assert.equal(eligible({...base,price:599},now),false);});
test('manual affiliate link does not need an invented rival price',()=>{assert.equal(eligible({...base,manual_id:'manual',competitor_price:null,expires_at:new Date(now+3600000).toISOString()},now),true);});
test('unknown hosts and deceptive domains never become redirect destinations',()=>{for(const u of ['http://amazon.com.tr','https://amazon.com.tr.evil.example','https://amazon.com.tr@evil.example','https://evil.example','https://amazon.com.tr:444/dp/X'])assert.equal(safeDestination(u,'amazon'),null);});
test('manual Hepsiburada short link remains intact',()=>assert.equal(safeDestination('https://app.hps.im/abc?ref=user','hepsiburada'),'https://app.hps.im/abc?ref=user'));
test('listing IDs are constrained',()=>{assert.equal(validListingId(base.id),true);assert.equal(validListingId('manual-'+base.id),true);assert.equal(validListingId('anything&select=*'),false);});
test('Turkish and English price punctuation',()=>{assert.equal(amount('799,90 TL'),799.9);assert.equal(amount('1.249,99 TL'),1249.99);assert.equal(amount('1,249.99'),1249.99);assert.equal(amount('0 TL'),null);});
test('product URLs require store HTTPS and preserve Trendyol seller',()=>{assert.equal(allowedProduct('https://www.trendyol.com/a-p-123','trendyol'),true);assert.equal(sameProduct('https://www.trendyol.com/a-p-123?merchantId=1','https://www.trendyol.com/b-p-123?merchantId=2','trendyol'),false);assert.equal(sameProduct('https://www.trendyol.com/a-p-123','https://www.trendyol.com/b-p-124','trendyol'),false);});
const schema=p=>'<script type="application/ld+json">'+JSON.stringify({'@type':'Product',offers:{'@type':'Offer',price:p,priceCurrency:'TRY',availability:'https://schema.org/InStock'}})+'</script>';
const doc=html=>parseHTML('<html><body>'+html+'</body></html>').document;
test('Ceel schema 428 versus purchase price 799 cannot verify',()=>{assert.throws(()=>parsePrice(doc('<h1>Ceel 2li</h1><span class="prc-box-sllng">799,90 TL</span>'+schema(428.26)),'trendyol','https://www.trendyol.com/x-p-123'),/mismatch/);});
test('Plus price cannot replace the regular purchase price',()=>{const d=doc('<h1>Ceel</h1><div class="plus-price"><span class="prc-box-sllng">775,90 TL</span></div><span class="prc-box-sllng">799,90 TL</span>'+schema(799.9));assert.equal(parsePrice(d,'trendyol','https://www.trendyol.com/x-p-123').price,799.9);});
test('JSON-LD alone is insufficient and ambiguous purchase prices are rejected',()=>{assert.throws(()=>parsePrice(doc('<h1>Ceel</h1>'+schema(428)),'trendyol','https://www.trendyol.com/x-p-123'));assert.throws(()=>parsePrice(doc('<h1>Ceel</h1><span class="prc-box-sllng">799 TL</span><span class="prc-box-dscntd">700 TL</span>'+schema(799)),'trendyol','https://www.trendyol.com/x-p-123'));});
test('Amazon ASIN and stock evidence are mandatory',()=>{const html='<h1 id="productTitle">Test</h1><input id="ASIN" value="B0CZ47VFR1"><input id="add-to-cart-button"><div id="availability">Stokta</div><div id="corePrice_feature_div"><span class="a-price"><span class="a-offscreen">400,00 TL</span></span></div>';assert.equal(parsePrice(doc(html),'amazon',base.product_url).price,400);assert.throws(()=>parsePrice(doc(html.replace('B0CZ47VFR1','B0CZ47VFR2')),'amazon',base.product_url));assert.throws(()=>parsePrice(doc(html.replace('Stokta','Stokta yok')),'amazon',base.product_url));});

test("unverified catalogue links do not imply a current price",()=>{const row={...base,status:"unverified",attempted_at:new Date(now-1000).toISOString(),error_code:"stock-unverified"};assert.equal(catalogueEligible(row,now),true);assert.equal(eligible(row,now),false);for(const error_code of ["store-http-404","product-identity-unverified","match-no-longer-approved","variant-identity-mismatch"])assert.equal(catalogueEligible({...row,error_code},now),false);assert.equal(catalogueEligible({...row,attempted_at:new Date(now-25*3600000).toISOString()},now),false);});

test("minimum quantity prices and missing buy buttons are rejected",()=>{const html='<h1>Product</h1><input id="ASIN" value="B0CZ47VFR1"><input id="add-to-cart-button"><div id="availability">Stokta</div><select id="quantity"><option value="2">2</option></select><div id="corePrice_feature_div"><span class="a-price"><span class="a-offscreen">400,00 TL</span></span></div>';assert.throws(()=>parsePrice(doc(html),"amazon",base.product_url),/minimum-quantity/);assert.throws(()=>parsePrice(doc(html.replace('<input id="add-to-cart-button">','').replace('value="2"','value="1"')),"amazon",base.product_url),/purchase-unavailable/);});
